/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller_Client;
import Controller.Controller_Produit;
import Controller.Controller_Stock;
import Controller.Controller_User;
import Controller.Controller_Vente;
import Dao.Dao_Client;
import Dao.Dao_Produit;
import Dao.Dao_Stock;
import Dao.Dao_User;
import Dao.Dao_Vente;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalFileChooserUI;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Josué Dik
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(this);
        Dao_Produit.AfficherTabProduit(jTableProduit);
        Dao_Client.AfficherTabClient(jTableClient);
        Dao_User.AfficherTabUser(jTableUser);
        Dao_Produit.AfficherTabProduitListes(jtableListeProduits);
        Dao_Stock.AfficherTabStock1(jTableStock1);
        Dao_Stock.RemplirLibelle(j002);
        Dao_Vente.RemplirLibelleVente(j0004);
        Dao_Stock.AfficherTabStock2(jTableStock2);
        AutoCompleteDecorator.decorate(j002);
        AutoCompleteDecorator.decorate(j0004);
        Dao_Vente.AfficherTabVente(jTableVente);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtbp1 = new javax.swing.JTabbedPane();
        jpStocks = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        j002 = new javax.swing.JComboBox<>();
        j004 = new javax.swing.JTextField();
        jbAjoutPr3 = new javax.swing.JButton();
        jbModifPro3 = new javax.swing.JButton();
        jbSuppPro3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableStock1 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        j003 = new javax.swing.JTextField();
        j001 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableStock2 = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jpSorties = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableVente = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        j0001 = new javax.swing.JComboBox<>();
        j0003 = new javax.swing.JComboBox<>();
        jbSuppPro4 = new javax.swing.JButton();
        jbModifPro4 = new javax.swing.JButton();
        jbAjoutPr4 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        j0002 = new com.toedter.calendar.JDateChooser();
        j0004 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        j0005 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        j0006 = new javax.swing.JTextField();
        j0007 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jpEntrees = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableProduit2 = new javax.swing.JTable();
        jtNomSci2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jcPridProduit2 = new javax.swing.JComboBox<>();
        jtPrLibPr2 = new javax.swing.JTextField();
        jcCatPr2 = new javax.swing.JComboBox<>();
        jcEmbPr2 = new javax.swing.JComboBox<>();
        jtDosePr2 = new javax.swing.JTextField();
        jbSuppPro5 = new javax.swing.JButton();
        jbModifPro5 = new javax.swing.JButton();
        jbAjoutPr5 = new javax.swing.JButton();
        jtFab2 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jpClients = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        j1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        j2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        j3 = new javax.swing.JComboBox<>();
        j4 = new javax.swing.JComboBox<>();
        j5 = new javax.swing.JTextField();
        jbAjoutPr1 = new javax.swing.JButton();
        jbModifPro1 = new javax.swing.JButton();
        jbSuppPro1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jpUsers = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        j01 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        j02 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        j03 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        j04 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        j05 = new javax.swing.JTextField();
        jbSuppPro2 = new javax.swing.JButton();
        jbModifPro2 = new javax.swing.JButton();
        jbAjoutPr2 = new javax.swing.JButton();
        j07 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        j06 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jpProduits = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduit = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcPridProduit = new javax.swing.JComboBox<>();
        jtPrLibPr = new javax.swing.JTextField();
        jtNomSci = new javax.swing.JTextField();
        jtFab = new javax.swing.JTextField();
        jcCatPr = new javax.swing.JComboBox<>();
        jcEmbPr = new javax.swing.JComboBox<>();
        jtDosePr = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jbAjoutPr = new javax.swing.JButton();
        jbModifPro = new javax.swing.JButton();
        jbSuppPro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtableListeProduits = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Affel Pharma");
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(32, 65, 89));
        jPanel1.setBorder(null);
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Affel Pharma");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, -2, 510, 60));

        jtbp1.setBackground(new java.awt.Color(153, 153, 153));
        jtbp1.setBorder(null);
        jtbp1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jtbp1.setFont(new java.awt.Font("Castellar", 3, 24)); // NOI18N
        jtbp1.setNextFocusableComponent(this);

        jpStocks.setBackground(new java.awt.Color(153, 153, 153));
        jpStocks.setBorder(null);
        jpStocks.setOpaque(false);
        jpStocks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j002.setEditable(true);
        j002.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AMOXY 500 MG CAPS" }));
        j002.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        j002.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                j002ItemStateChanged(evt);
            }
        });
        j002.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                j002PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        j002.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j002MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                j002MouseEntered(evt);
            }
        });
        j002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j002ActionPerformed(evt);
            }
        });
        jPanel7.add(j002, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 250, 50));

        j004.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j004.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j004.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(j004, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 210, 50));

        jbAjoutPr3.setText("Ajouter / Enregistrer");
        jbAjoutPr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAjoutPr3MouseClicked(evt);
            }
        });
        jbAjoutPr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjoutPr3ActionPerformed(evt);
            }
        });
        jPanel7.add(jbAjoutPr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 200, 40));

        jbModifPro3.setText("Modifier / Mettre a jour");
        jbModifPro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifPro3ActionPerformed(evt);
            }
        });
        jPanel7.add(jbModifPro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 200, 40));

        jbSuppPro3.setText("Effacer / Supprimer Produit");
        jbSuppPro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuppPro3ActionPerformed(evt);
            }
        });
        jPanel7.add(jbSuppPro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 200, 40));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recurring Appointment_48px_2.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 90, 150));

        jTableStock1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableStock1.setGridColor(new java.awt.Color(51, 204, 255));
        jTableStock1.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTableStock1.getTableHeader().setReorderingAllowed(false);
        jTableStock1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStock1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableStock1);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1050, 430));

        jLabel25.setBackground(new java.awt.Color(204, 204, 204));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel25.setText("Libelle Produit:");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        jLabel26.setBackground(new java.awt.Color(204, 204, 204));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel26.setText("idProduit:");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        jLabel27.setBackground(new java.awt.Color(204, 204, 204));
        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel27.setText("Quantité Disponible");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 120, 20));

        jLabel28.setBackground(new java.awt.Color(204, 204, 204));
        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel28.setText("Prix Unitaire");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 120, 40));

        j003.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j003.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j003.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(j003, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 210, 50));

        j001.setEditable(true);
        j001.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        j001.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        j001.setEnabled(false);
        jPanel7.add(j001, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 250, 50));

        jTabbedPane2.addTab("GESTION STOCK", jPanel7);

        jPanel8.setOpaque(false);

        jTableStock2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableStock2.setGridColor(new java.awt.Color(51, 204, 255));
        jTableStock2.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jScrollPane6.setViewportView(jTableStock2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane2.addTab("STOCK DISPONIBLE", jPanel8);

        jPanel18.setOpaque(false);
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("PRODUITS RECHERCHES", jPanel18);

        jPanel19.setOpaque(false);
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("PRODUITS A ACHETER", jPanel19);

        jpStocks.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 660));

        jtbp1.addTab("STOCKS", jpStocks);

        jpSorties.setBackground(new java.awt.Color(153, 153, 153));
        jpSorties.setBorder(null);
        jpSorties.setOpaque(false);
        jpSorties.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(null);
        jTabbedPane1.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableVente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableVente.setGridColor(new java.awt.Color(51, 204, 255));
        jTableVente.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTableVente.getTableHeader().setReorderingAllowed(false);
        jTableVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVenteMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTableVente);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1050, 430));

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel29.setText("idProduit");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 20));

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel31.setText("idVente");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        j0001.setEditable(true);
        j0001.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        j0001.setEnabled(false);
        jPanel2.add(j0001, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, 30));

        j0003.setEditable(true);
        j0003.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        j0003.setEnabled(false);
        jPanel2.add(j0003, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, 30));

        jbSuppPro4.setText("Effacer / Supprimer Produit");
        jbSuppPro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuppPro4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbSuppPro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 200, 30));

        jbModifPro4.setText("Modifier / Mettre a jour");
        jbModifPro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifPro4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbModifPro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 200, 30));

        jbAjoutPr4.setText("Ajouter / Enregistrer");
        jbAjoutPr4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAjoutPr4MouseClicked(evt);
            }
        });
        jbAjoutPr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjoutPr4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbAjoutPr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 200, 30));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recurring Appointment_48px_2.png"))); // NOI18N
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 70, 110));

        j0002.setToolTipText("Choisir la date");
        j0002.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(j0002, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 220, 30));

        j0004.setEditable(true);
        j0004.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        j0004.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                j0004PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel2.add(j0004, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 30));

        jLabel39.setBackground(new java.awt.Color(204, 204, 204));
        jLabel39.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel39.setText("Date");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        jLabel40.setBackground(new java.awt.Color(204, 204, 204));
        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel40.setText("Libelle Produit");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 30));

        jLabel41.setBackground(new java.awt.Color(204, 204, 204));
        jLabel41.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel41.setText("Prix Unitaire");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 90, 30));

        j0005.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j0005.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j0005.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j0005.setEnabled(false);
        jPanel2.add(j0005, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 150, 30));

        jLabel42.setBackground(new java.awt.Color(204, 204, 204));
        jLabel42.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel42.setText("Quantité");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 90, 50));

        j0006.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j0006.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j0006.setToolTipText("Saisir la quantite");
        j0006.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(j0006, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 150, 30));

        j0007.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j0007.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j0007.setToolTipText("Saisir la quantite");
        j0007.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j0007.setEnabled(false);
        jPanel2.add(j0007, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 110, 30));

        jLabel43.setBackground(new java.awt.Color(204, 204, 204));
        jLabel43.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel43.setText("Quantité disponible");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 120, 50));

        jTabbedPane1.addTab("VENTE", jPanel2);

        jPanel3.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("LISTE VENTE", jPanel3);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("EMPRUNT", jPanel9);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("LISTE EMPRUNT", jPanel12);

        jpSorties.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 660));

        jtbp1.addTab("SORTIES", jpSorties);

        jpEntrees.setBorder(null);
        jpEntrees.setOpaque(false);

        jTabbedPane5.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProduit2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProduit2.setGridColor(new java.awt.Color(51, 204, 255));
        jTableProduit2.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTableProduit2.getTableHeader().setReorderingAllowed(false);
        jTableProduit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProduit2MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTableProduit2);

        jPanel6.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1050, 430));

        jtNomSci2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtNomSci2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNomSci2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jtNomSci2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 40));

        jLabel34.setBackground(new java.awt.Color(204, 204, 204));
        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel34.setText("DCI");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 20));

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel35.setText("Libellé Produit :");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        jLabel36.setBackground(new java.awt.Color(204, 204, 204));
        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel36.setText("idProduit :");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        jcPridProduit2.setEditable(true);
        jcPridProduit2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jcPridProduit2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jcPridProduit2.setEnabled(false);
        jPanel6.add(jcPridProduit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 160, 40));

        jtPrLibPr2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtPrLibPr2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtPrLibPr2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jtPrLibPr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 40));

        jcCatPr2.setEditable(true);
        jcCatPr2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anésthesian", "Antidépresseurs", "Antibiotiques", "Antalgiques", "Antiviraux", "Anti-diurétiques\t", "Anti-inflammatoires\t", "Antihistaminiques", "Antipyrétiques", "Anxiolytiques", "Antirétroviraux", "Bronchodilatateurs", "Diurétiques", "Laxatif", "Psychotropes", "Sédatifs", "Vasopresseurs", " " }));
        jcCatPr2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel6.add(jcCatPr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 40));

        jcEmbPr2.setEditable(true);
        jcEmbPr2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Capsules", "Comprimés", "Flacon", "Goutte", "Injection", "Suppositoire", " ", " ", " " }));
        jcEmbPr2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel6.add(jcEmbPr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 150, 40));

        jtDosePr2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtDosePr2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtDosePr2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jtDosePr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 150, 40));

        jbSuppPro5.setText("Effacer / Supprimer Produit");
        jbSuppPro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuppPro5ActionPerformed(evt);
            }
        });
        jPanel6.add(jbSuppPro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 148, 200, 30));

        jbModifPro5.setText("Modifier / Mettre a jour");
        jbModifPro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifPro5ActionPerformed(evt);
            }
        });
        jPanel6.add(jbModifPro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 200, 30));

        jbAjoutPr5.setText("Ajouter / Enregistrer");
        jbAjoutPr5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAjoutPr5MouseClicked(evt);
            }
        });
        jbAjoutPr5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjoutPr5ActionPerformed(evt);
            }
        });
        jPanel6.add(jbAjoutPr5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 200, 30));

        jtFab2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtFab2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtFab2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jtFab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 150, 40));

        jLabel37.setBackground(new java.awt.Color(204, 204, 204));
        jLabel37.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel37.setText("Fabriquant :");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 20));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recurring Appointment_48px_2.png"))); // NOI18N
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 70, 110));

        jTabbedPane5.addTab("GESTION ACHATS", jPanel6);

        jPanel13.setFocusable(false);
        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane5.addTab("LISTE ACHATS", jPanel13);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane5.addTab("GESTION ACHATS A CREDIT", jPanel14);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane5.addTab("LISTE DES ACHATS A CREDIT", jPanel15);

        javax.swing.GroupLayout jpEntreesLayout = new javax.swing.GroupLayout(jpEntrees);
        jpEntrees.setLayout(jpEntreesLayout);
        jpEntreesLayout.setHorizontalGroup(
            jpEntreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        jpEntreesLayout.setVerticalGroup(
            jpEntreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEntreesLayout.createSequentialGroup()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );

        jtbp1.addTab("ENTREES", null, jpEntrees, "Les entrées");

        jpClients.setOpaque(false);
        jpClients.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane4.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("idClient:");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        j1.setEditable(true);
        j1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        j1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        j1.setEnabled(false);
        jPanel11.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 160, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Noms Clients :");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Type Client :");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 20));

        j2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 40));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Commune Client :");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 150, 40));

        j3.setEditable(true);
        j3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIDELE", "OCCASIONEL", "PASSAGER", " ", " ", " " }));
        j3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel11.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 40));

        j4.setEditable(true);
        j4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONT NGAFULA", "NGALIEMA", "BUMBU", "KINSHASA", "BARUMBU", "NSELE", "GOMBE", "LIMETE", "KASAVUBU", " " }));
        j4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel11.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 180, 40));

        j5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 180, 90));

        jbAjoutPr1.setText("Ajouter / Enregistrer");
        jbAjoutPr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAjoutPr1MouseClicked(evt);
            }
        });
        jbAjoutPr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjoutPr1ActionPerformed(evt);
            }
        });
        jPanel11.add(jbAjoutPr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 200, 40));

        jbModifPro1.setText("Modifier / Mettre a jour");
        jbModifPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifPro1ActionPerformed(evt);
            }
        });
        jPanel11.add(jbModifPro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 200, 50));

        jbSuppPro1.setText("Effacer / Supprimer Produit");
        jbSuppPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuppPro1ActionPerformed(evt);
            }
        });
        jPanel11.add(jbSuppPro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 200, 40));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recurring Appointment_48px_2.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 90, 150));

        jTableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableClient.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTableClient.getTableHeader().setReorderingAllowed(false);
        jTableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClient);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1050, 430));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Adresse :");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, 30));

        jTabbedPane4.addTab("GESTION CLIENTS", jPanel11);

        jPanel16.setOpaque(false);
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane4.addTab("LISTE DES CLIENTS ", jPanel16);

        jpClients.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 660));

        jtbp1.addTab("CLIENTS", jpClients);

        jpUsers.setOpaque(false);
        jpUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane6.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("idUtilisateur:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        j01.setEditable(true);
        j01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        j01.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        j01.setEnabled(false);
        jPanel5.add(j01, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 160, 40));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Nom Utilisateur :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        j02.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(j02, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 40));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Postnom Utilisateur :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 20));

        j03.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(j03, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 40));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setText("Type Utilisateur :");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 150, 40));

        j04.setEditable(true);
        j04.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER", "ADMIN" }));
        j04.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel5.add(j04, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 190, 40));

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setText("Email utilisateur :");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 160, 30));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setText("Login Utilisateur :");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 170, 20));

        j05.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        j05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(j05, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 190, 40));

        jbSuppPro2.setText("Effacer / Supprimer Produit");
        jbSuppPro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuppPro2ActionPerformed(evt);
            }
        });
        jPanel5.add(jbSuppPro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 148, 200, 30));

        jbModifPro2.setText("Modifier / Mettre a jour");
        jbModifPro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifPro2ActionPerformed(evt);
            }
        });
        jPanel5.add(jbModifPro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 200, 30));

        jbAjoutPr2.setText("Ajouter / Enregistrer");
        jbAjoutPr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAjoutPr2MouseClicked(evt);
            }
        });
        jbAjoutPr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjoutPr2ActionPerformed(evt);
            }
        });
        jPanel5.add(jbAjoutPr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 200, 30));

        j07.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j07ActionPerformed(evt);
            }
        });
        jPanel5.add(j07, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 160, 40));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel22.setText("Mot de Passe :");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 90, 20));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recurring Appointment_48px_2.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 70, 110));

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableUser.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTableUser.getTableHeader().setReorderingAllowed(false);
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableUser);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1050, 430));

        j06.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        j06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(j06, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 190, 40));

        jTabbedPane6.addTab("GESTION UTILISATEURS", jPanel5);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane6.addTab("LISTE DES UTILISATEURS", jPanel17);

        jpUsers.add(jTabbedPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 660));

        jtbp1.addTab("UTILISATEURS", jpUsers);

        jpProduits.setBorder(null);
        jpProduits.setOpaque(false);

        jTabbedPane3.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProduit.setGridColor(new java.awt.Color(51, 204, 255));
        jTableProduit.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jTableProduit.getTableHeader().setReorderingAllowed(false);
        jTableProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduit);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1050, 430));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("idProduit :");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Libellé Produit :");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("DCI");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 20));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Type/Categorie Produit :");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 10, 150, 40));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Emballage Produit :");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 160, 30));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Dose Produit :");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 170, 20));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Fabriquant :");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 20));

        jcPridProduit.setEditable(true);
        jcPridProduit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jcPridProduit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jcPridProduit.setEnabled(false);
        jPanel10.add(jcPridProduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 160, 40));

        jtPrLibPr.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtPrLibPr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtPrLibPr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.add(jtPrLibPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 40));

        jtNomSci.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtNomSci.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNomSci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.add(jtNomSci, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, 40));

        jtFab.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtFab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtFab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.add(jtFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 150, 40));

        jcCatPr.setEditable(true);
        jcCatPr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anésthesian", "Antidépresseurs", "Antibiotiques", "Antalgiques", "Antiviraux", "Anti-diurétiques\t", "Anti-inflammatoires\t", "Antihistaminiques", "Antipyrétiques", "Anxiolytiques", "Antirétroviraux", "Bronchodilatateurs", "Diurétiques", "Laxatif", "Psychotropes", "Sédatifs", "Vasopresseurs", " " }));
        jcCatPr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel10.add(jcCatPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 40));

        jcEmbPr.setEditable(true);
        jcEmbPr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Capsules", "Comprimés", "Flacon", "Goutte", "Injection", "Suppositoire", " ", " ", " " }));
        jcEmbPr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel10.add(jcEmbPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 150, 40));

        jtDosePr.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jtDosePr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtDosePr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.add(jtDosePr, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 150, 40));
        jPanel10.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 10));
        jPanel10.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 160, 10));
        jPanel10.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 150, 10));
        jPanel10.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, 10));

        jbAjoutPr.setText("Ajouter / Enregistrer");
        jbAjoutPr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAjoutPrMouseClicked(evt);
            }
        });
        jbAjoutPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjoutPrActionPerformed(evt);
            }
        });
        jPanel10.add(jbAjoutPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 200, 30));

        jbModifPro.setText("Modifier / Mettre a jour");
        jbModifPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifProActionPerformed(evt);
            }
        });
        jPanel10.add(jbModifPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 200, 30));

        jbSuppPro.setText("Effacer / Supprimer Produit");
        jbSuppPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuppProActionPerformed(evt);
            }
        });
        jPanel10.add(jbSuppPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 148, 200, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recurring Appointment_48px_2.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 70, 110));

        jTabbedPane3.addTab("RENSEIGNEMENT PRODUITS", jPanel10);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtableListeProduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableListeProduits.setGridColor(new java.awt.Color(51, 204, 255));
        jtableListeProduits.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jtableListeProduits.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtableListeProduits);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1050, 630));

        jTabbedPane3.addTab("LISTE PRODUITS SUR LE MARCHE", jPanel4);

        javax.swing.GroupLayout jpProduitsLayout = new javax.swing.GroupLayout(jpProduits);
        jpProduits.setLayout(jpProduitsLayout);
        jpProduitsLayout.setHorizontalGroup(
            jpProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProduitsLayout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jpProduitsLayout.setVerticalGroup(
            jpProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProduitsLayout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jtbp1.addTab("PRODUITS", jpProduits);

        jPanel1.add(jtbp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1270, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1274, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAjoutPrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAjoutPrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAjoutPrMouseClicked

    private void jbAjoutPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjoutPrActionPerformed
        // TODO add your handling code here:
        int a=Dao_Produit.VerifierRedondance(jtPrLibPr);
        if (!(a==1)) {
        Controller_Produit.Enregistrer(jcPridProduit, jtPrLibPr, jtNomSci, jcCatPr, jcEmbPr, jtDosePr, jtFab);
        Dao_Produit.AfficherTabProduit(jTableProduit);
        Dao_Produit.AfficherTabProduitListes(jtableListeProduits);
        Dao_Stock.RemplirLibelle(j002);
        }
        else{
            JOptionPane.showMessageDialog(null, "Ce produit existe deja");
        }
        
    }//GEN-LAST:event_jbAjoutPrActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Dao_Produit.AfficherTabProduit(jTableProduit);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jbModifProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifProActionPerformed
        // TODO add your handling code here:
        Controller_Produit.Modifier(jcPridProduit, jtPrLibPr, jtNomSci, jcCatPr, jcEmbPr, jtDosePr, jtFab);
        Dao_Produit.AfficherTabProduit(jTableProduit);
        Dao_Produit.AfficherTabProduitListes(jtableListeProduits);
        Dao_Produit.AfficherTabProduitListes(jtableListeProduits);
        Dao_Stock.RemplirLibelle(j002);
    }//GEN-LAST:event_jbModifProActionPerformed

    private void jTableProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProduitMouseClicked
        // TODO add your handling code here:
        Controller_Produit.Remplir(jTableProduit, jcPridProduit, jtPrLibPr, jtNomSci, jcCatPr, jcEmbPr, jtDosePr, jtFab);
    }//GEN-LAST:event_jTableProduitMouseClicked

    private void jbSuppProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuppProActionPerformed
        // TODO add your handling code here:
        Controller_Produit.Supprimer(jcPridProduit);
        Dao_Produit.AfficherTabProduit(jTableProduit);
        Dao_Stock.RemplirLibelle(j002);
    }//GEN-LAST:event_jbSuppProActionPerformed

    private void jbAjoutPr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAjoutPr1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAjoutPr1MouseClicked

    private void jbAjoutPr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjoutPr1ActionPerformed
        // TODO add your handling code here:
        int b=Controller_Client.VerifierChamp(j2,j5);
        int a=Dao_Client.VerifierRedondance(j2);
        if (b==1) {
            if (!(a==1)) {
        Controller_Client.Enregistrer(j1, j2, j3, j4, j5);
        Dao_Client.AfficherTabClient(jTableClient);
        }
        else{
            JOptionPane.showMessageDialog(null, "Ce client existe deja");
        }
        }
        else{
        JOptionPane.showMessageDialog(null, "Remplir tous les champs");
        }  
    }//GEN-LAST:event_jbAjoutPr1ActionPerformed

    private void jbModifPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifPro1ActionPerformed
        // TODO add your handling code here:
        Controller_Client.Modifier(j1, j2, j3, j4, j5);
        Dao_Client.AfficherTabClient(jTableClient);
    }//GEN-LAST:event_jbModifPro1ActionPerformed

    private void jbSuppPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuppPro1ActionPerformed
        // TODO add your handling code here:
        Controller_Client.Supprimer(j1);
        Dao_Client.AfficherTabClient(jTableClient);
    }//GEN-LAST:event_jbSuppPro1ActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        Dao_Client.AfficherTabClient(jTableClient);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jTableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientMouseClicked
        // TODO add your handling code here:
        Controller_Client.Remplir(jTableClient, j1, j2, j3, j4, j5);
    }//GEN-LAST:event_jTableClientMouseClicked

    private void jbSuppPro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuppPro2ActionPerformed
        // TODO add your handling code here:
        Controller_User.Supprimer(j01);
        Dao_User.AfficherTabUser(jTableUser);
    }//GEN-LAST:event_jbSuppPro2ActionPerformed

    private void jbModifPro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifPro2ActionPerformed
        // TODO add your handling code here:
        Controller_User.Modifier2(j01, j02, j03, j04, j05, j06,j07);
        Dao_User.AfficherTabUser(jTableUser);
    }//GEN-LAST:event_jbModifPro2ActionPerformed

    private void jbAjoutPr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAjoutPr2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAjoutPr2MouseClicked

    private void jbAjoutPr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjoutPr2ActionPerformed
        // TODO add your handling code here:
        int a=Dao_User.VerifierRedondance(j02, j03);
        if (!(a==1)) {
        Controller_User.Enregistrer2(j01, j02, j03, j04, j05, j06, j07);
        Dao_User.AfficherTabUser(jTableUser);
        }
        else{
            JOptionPane.showMessageDialog(null, "Cet utilisateur existe deja");
        }
        
    }//GEN-LAST:event_jbAjoutPr2ActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        Dao_User.AfficherTabUser(jTableUser);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
        // TODO add your handling code here:
        Controller_User.Remplir(jTableUser, j01, j02, j03, j04, j05, j06, j07);
        
    }//GEN-LAST:event_jTableUserMouseClicked

    private void j07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j07ActionPerformed

    private void jbAjoutPr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAjoutPr3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAjoutPr3MouseClicked

    private void jbAjoutPr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjoutPr3ActionPerformed
        // TODO add your handling code here:
        int b=Controller_Stock.VerifierChamps(j003, j004);
        int a=Dao_Stock.VerifierRedondance(j002);
        if (b==1) {
            if (!(a==1)) {
        Controller_Stock.Enregister(j001,j002, j003, j004);
        Dao_Stock.AfficherTabStock1(jTableStock1);
        Dao_Stock.AfficherTabStock2(jTableStock2);
        Dao_Vente.RemplirLibelleVente(j0004);
        }
        else{
            JOptionPane.showMessageDialog(null, "Ce produit existe deja");
        }
        }
        else{
        JOptionPane.showMessageDialog(null, "Remplir tous les champs");
        }
        
        
    }//GEN-LAST:event_jbAjoutPr3ActionPerformed

    private void jbModifPro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifPro3ActionPerformed
        // TODO add your handling code here:
        Controller_Stock.Modifier(j001, j002, j003, j004);
        Dao_Stock.AfficherTabStock1(jTableStock1);
        Dao_Stock.AfficherTabStock2(jTableStock2);
        Dao_Vente.RemplirLibelleVente(j0004);
    }//GEN-LAST:event_jbModifPro3ActionPerformed

    private void jbSuppPro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuppPro3ActionPerformed
        // TODO add your handling code here:
        Controller_Stock.Supprimer(j001);
        Dao_Stock.AfficherTabStock1(jTableStock1);
        Dao_Stock.AfficherTabStock2(jTableStock2);
        Dao_Vente.RemplirLibelleVente(j0004);
    }//GEN-LAST:event_jbSuppPro3ActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        Dao_Stock.AfficherTabStock1(jTableStock1);
        Dao_Stock.RemplirLibelle(j002);
        Dao_Stock.AfficherTabStock2(jTableStock2);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jTableStock1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStock1MouseClicked
        // TODO add your handling code here:
        Controller_Stock.Remplir(jTableStock1, j001, j002, j003, j004);
    }//GEN-LAST:event_jTableStock1MouseClicked

    private void j002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j002ActionPerformed
        // TODO add your handling code here:
//        Dao_Stock.RemplirIdProduit(j001, j002);
    }//GEN-LAST:event_j002ActionPerformed

    private void j002MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j002MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_j002MouseClicked

    private void j002MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j002MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_j002MouseEntered

    private void j002PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_j002PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        Dao_Stock.RemplirIdProduit(j001, j002);
    }//GEN-LAST:event_j002PopupMenuWillBecomeInvisible

    private void jTableVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVenteMouseClicked
        // TODO add your handling code here:
        Controller_Vente.Remplir(jTableVente, j0001, j0002, j0003, j0004, j0005, j0006);
    }//GEN-LAST:event_jTableVenteMouseClicked

    private void jbSuppPro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuppPro4ActionPerformed
        // TODO add your handling code here:
        Controller_Vente.Supprimer(j0001);
        Dao_Stock.AfficherTabStock1(jTableStock1);
        Dao_Stock.RemplirLibelle(j002);
        Dao_Vente.AfficherTabVente(jTableVente);
        Dao_Stock.AfficherTabStock2(jTableStock2);
    }//GEN-LAST:event_jbSuppPro4ActionPerformed

    private void jbModifPro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifPro4ActionPerformed
        try {
            // TODO add your handling code here:
            Controller_Vente.Modifier(j0001, j0002, j0003, j0004, j0005, j0006);
            Dao_Vente.AfficherTabVente(jTableVente);
            Dao_Stock.AfficherTabStock1(jTableStock1);
        Dao_Stock.RemplirLibelle(j002);
        Dao_Stock.AfficherTabStock2(jTableStock2);
        } catch (ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbModifPro4ActionPerformed

    private void jbAjoutPr4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAjoutPr4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAjoutPr4MouseClicked

    private void jbAjoutPr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjoutPr4ActionPerformed
        try {
            // TODO add your handling code here:
            Controller_Vente.Enregistrer(j0002, j0003, j0004, j0005, j0006);
            Dao_Stock.AfficherTabStock1(jTableStock1);
            Dao_Vente.AfficherTabVente(jTableVente);
            Dao_Stock.AfficherTabStock1(jTableStock1);
            Dao_Stock.AfficherTabStock2(jTableStock2);
          
            Dao_Stock.RemplirLibelle(j002);
        } catch (ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbAjoutPr4ActionPerformed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        Dao_Vente.AfficherTabVente(jTableVente);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jTableProduit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProduit2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableProduit2MouseClicked

    private void jbSuppPro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuppPro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSuppPro5ActionPerformed

    private void jbModifPro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifPro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbModifPro5ActionPerformed

    private void jbAjoutPr5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAjoutPr5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAjoutPr5MouseClicked

    private void jbAjoutPr5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjoutPr5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAjoutPr5ActionPerformed

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    private void j002ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_j002ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_j002ItemStateChanged

    private void j0004PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_j0004PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        Dao_Vente.RemplirIdProduit(j0003, j0004,j0005,j0007);
    }//GEN-LAST:event_j0004PopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> j0001;
    private com.toedter.calendar.JDateChooser j0002;
    private javax.swing.JComboBox<String> j0003;
    private javax.swing.JComboBox<String> j0004;
    private javax.swing.JTextField j0005;
    private javax.swing.JTextField j0006;
    private javax.swing.JTextField j0007;
    private javax.swing.JComboBox<String> j001;
    private javax.swing.JComboBox<String> j002;
    private javax.swing.JTextField j003;
    private javax.swing.JTextField j004;
    private javax.swing.JComboBox<String> j01;
    private javax.swing.JTextField j02;
    private javax.swing.JTextField j03;
    private javax.swing.JComboBox<String> j04;
    private javax.swing.JTextField j05;
    private javax.swing.JTextField j06;
    private javax.swing.JTextField j07;
    private javax.swing.JComboBox<String> j1;
    private javax.swing.JTextField j2;
    private javax.swing.JComboBox<String> j3;
    private javax.swing.JComboBox<String> j4;
    private javax.swing.JTextField j5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTableClient;
    private javax.swing.JTable jTableProduit;
    private javax.swing.JTable jTableProduit2;
    private javax.swing.JTable jTableStock1;
    private javax.swing.JTable jTableStock2;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTable jTableVente;
    private javax.swing.JButton jbAjoutPr;
    private javax.swing.JButton jbAjoutPr1;
    private javax.swing.JButton jbAjoutPr2;
    private javax.swing.JButton jbAjoutPr3;
    private javax.swing.JButton jbAjoutPr4;
    private javax.swing.JButton jbAjoutPr5;
    private javax.swing.JButton jbModifPro;
    private javax.swing.JButton jbModifPro1;
    private javax.swing.JButton jbModifPro2;
    private javax.swing.JButton jbModifPro3;
    private javax.swing.JButton jbModifPro4;
    private javax.swing.JButton jbModifPro5;
    private javax.swing.JButton jbSuppPro;
    private javax.swing.JButton jbSuppPro1;
    private javax.swing.JButton jbSuppPro2;
    private javax.swing.JButton jbSuppPro3;
    private javax.swing.JButton jbSuppPro4;
    private javax.swing.JButton jbSuppPro5;
    private javax.swing.JComboBox<String> jcCatPr;
    private javax.swing.JComboBox<String> jcCatPr2;
    private javax.swing.JComboBox<String> jcEmbPr;
    private javax.swing.JComboBox<String> jcEmbPr2;
    private javax.swing.JComboBox<String> jcPridProduit;
    private javax.swing.JComboBox<String> jcPridProduit2;
    private javax.swing.JPanel jpClients;
    private javax.swing.JPanel jpEntrees;
    private javax.swing.JPanel jpProduits;
    private javax.swing.JPanel jpSorties;
    private javax.swing.JPanel jpStocks;
    private javax.swing.JPanel jpUsers;
    private javax.swing.JTextField jtDosePr;
    private javax.swing.JTextField jtDosePr2;
    private javax.swing.JTextField jtFab;
    private javax.swing.JTextField jtFab2;
    private javax.swing.JTextField jtNomSci;
    private javax.swing.JTextField jtNomSci2;
    private javax.swing.JTextField jtPrLibPr;
    private javax.swing.JTextField jtPrLibPr2;
    private javax.swing.JTable jtableListeProduits;
    private javax.swing.JTabbedPane jtbp1;
    // End of variables declaration//GEN-END:variables
}
